const CASES_COLOR = "#d9a629";
const DEATHS_COLOR = "#ba2020";
const ESTIMATIVE_COLOR = "#273b8c";
const RECOVERED_COLOR = "#66bb6a";
const SUSPECTED_COLOR = "#d4e157";

export {
  CASES_COLOR,
  DEATHS_COLOR,
  ESTIMATIVE_COLOR,
  RECOVERED_COLOR,
  SUSPECTED_COLOR
}